name: Uffizzi Cluster

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]


permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build-image:
    name: Build and Push `nodejs` Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          # An anonymous, emphemeral registry built on ttl.sh
          images: jfu888/dockerjs
          tags: type=raw,value=48h
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Image to Uffizzi Ephemeral Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./
